language: node_js
node_js:
  - "node"

before_install:
  - rvm install 2.5.0

install:
  - ./ci-install.sh

script:
  - ./ci-run.sh

notifications:
  email:
    on_failure: always
    on_success: never
